/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PVmoduleService } from "../pVmodule.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PVmoduleCreateInput } from "./PVmoduleCreateInput";
import { PVmodule } from "./PVmodule";
import { PVmoduleFindManyArgs } from "./PVmoduleFindManyArgs";
import { PVmoduleWhereUniqueInput } from "./PVmoduleWhereUniqueInput";
import { PVmoduleUpdateInput } from "./PVmoduleUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PVmoduleControllerBase {
  constructor(
    protected readonly service: PVmoduleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PVmodule })
  @nestAccessControl.UseRoles({
    resource: "PVmodule",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPVmodule(
    @common.Body() data: PVmoduleCreateInput
  ): Promise<PVmodule> {
    return await this.service.createPVmodule({
      data: {
        ...data,

        manufacturer: {
          connect: data.manufacturer,
        },
      },
      select: {
        cellQuantity: true,
        id: true,

        manufacturer: {
          select: {
            id: true,
          },
        },

        maxPvVoltage: true,
        model: true,
        ratedPower: true,
        temperatureHighC: true,
        temperatureLowC: true,
        unitPrice: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PVmodule] })
  @ApiNestedQuery(PVmoduleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PVmodule",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pVmodules(@common.Req() request: Request): Promise<PVmodule[]> {
    const args = plainToClass(PVmoduleFindManyArgs, request.query);
    return this.service.pVmodules({
      ...args,
      select: {
        cellQuantity: true,
        id: true,

        manufacturer: {
          select: {
            id: true,
          },
        },

        maxPvVoltage: true,
        model: true,
        ratedPower: true,
        temperatureHighC: true,
        temperatureLowC: true,
        unitPrice: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PVmodule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PVmodule",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pVmodule(
    @common.Param() params: PVmoduleWhereUniqueInput
  ): Promise<PVmodule | null> {
    const result = await this.service.pVmodule({
      where: params,
      select: {
        cellQuantity: true,
        id: true,

        manufacturer: {
          select: {
            id: true,
          },
        },

        maxPvVoltage: true,
        model: true,
        ratedPower: true,
        temperatureHighC: true,
        temperatureLowC: true,
        unitPrice: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PVmodule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PVmodule",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePVmodule(
    @common.Param() params: PVmoduleWhereUniqueInput,
    @common.Body() data: PVmoduleUpdateInput
  ): Promise<PVmodule | null> {
    try {
      return await this.service.updatePVmodule({
        where: params,
        data: {
          ...data,

          manufacturer: {
            connect: data.manufacturer,
          },
        },
        select: {
          cellQuantity: true,
          id: true,

          manufacturer: {
            select: {
              id: true,
            },
          },

          maxPvVoltage: true,
          model: true,
          ratedPower: true,
          temperatureHighC: true,
          temperatureLowC: true,
          unitPrice: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PVmodule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PVmodule",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePVmodule(
    @common.Param() params: PVmoduleWhereUniqueInput
  ): Promise<PVmodule | null> {
    try {
      return await this.service.deletePVmodule({
        where: params,
        select: {
          cellQuantity: true,
          id: true,

          manufacturer: {
            select: {
              id: true,
            },
          },

          maxPvVoltage: true,
          model: true,
          ratedPower: true,
          temperatureHighC: true,
          temperatureLowC: true,
          unitPrice: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
