/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SubCategoryService } from "../subCategory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SubCategoryCreateInput } from "./SubCategoryCreateInput";
import { SubCategory } from "./SubCategory";
import { SubCategoryFindManyArgs } from "./SubCategoryFindManyArgs";
import { SubCategoryWhereUniqueInput } from "./SubCategoryWhereUniqueInput";
import { SubCategoryUpdateInput } from "./SubCategoryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SubCategoryControllerBase {
  constructor(
    protected readonly service: SubCategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SubCategory })
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSubCategory(
    @common.Body() data: SubCategoryCreateInput
  ): Promise<SubCategory> {
    return await this.service.createSubCategory({
      data: {
        ...data,

        category: {
          connect: data.category,
        },
      },
      select: {
        category: {
          select: {
            id: true,
          },
        },

        id: true,
        label: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SubCategory] })
  @ApiNestedQuery(SubCategoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async subCategories(@common.Req() request: Request): Promise<SubCategory[]> {
    const args = plainToClass(SubCategoryFindManyArgs, request.query);
    return this.service.subCategories({
      ...args,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        id: true,
        label: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SubCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async subCategory(
    @common.Param() params: SubCategoryWhereUniqueInput
  ): Promise<SubCategory | null> {
    const result = await this.service.subCategory({
      where: params,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        id: true,
        label: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SubCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSubCategory(
    @common.Param() params: SubCategoryWhereUniqueInput,
    @common.Body() data: SubCategoryUpdateInput
  ): Promise<SubCategory | null> {
    try {
      return await this.service.updateSubCategory({
        where: params,
        data: {
          ...data,

          category: {
            connect: data.category,
          },
        },
        select: {
          category: {
            select: {
              id: true,
            },
          },

          id: true,
          label: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SubCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SubCategory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSubCategory(
    @common.Param() params: SubCategoryWhereUniqueInput
  ): Promise<SubCategory | null> {
    try {
      return await this.service.deleteSubCategory({
        where: params,
        select: {
          category: {
            select: {
              id: true,
            },
          },

          id: true,
          label: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
